### ISSUE TITLE
SolasAI disparity calculation by decile

### ISSUE THREAD

**Issue by stupidoge** [SolasAI/solas-ai-disparity#3]
Hi Authors,

I have several questions because I cannot find any detailed explain from your document. 

1. the `outcome` attribute could be what value? could this be decile score value from 1 to 10? 
 2.I cannot find any details about the function of Adverse Impact Ratio by Quantile function, how the quantile calculated? By model output score distribution by decile? Or equally classified those output from 1-10? 

By the way, I also write an internal functions, I got the decile output by myself, and use the function `adverse_impact_ratio`, but outcome set as decile column (only output 1-10), and add a for loop to accumulatively calculate decile, but the result is different fron your `adverse_impact_ratio_by_quantile`. Could you illustrate this function in more details? thanks. 

```
airq = sd.adverse_impact_ratio_by_quantile(
    outcome=data["Prediction"],
    air_threshold=0.8,
    percent_difference_threshold=0.0,
    quantiles=[decile / 10 for decile in range(1, 11)],
    lower_score_favorable=True,
    **reused_arguments,
)
airq
```

**Comment by stupidoge** [comment]
@eric-peacock @ebb-earl-co @nickpschmidt 
@mikewilkerson-solas  Hi all, could you help me figure this out? thanks.

**Comment by mikewilkerson-solas** [comment]
Hi! Thanks for opening an issue.

`outcome` in the `adverse_impact_ratio` calculation is an indicator of whether a person has received a "favorable" outcome. It's a Pandas `Series` where 1 represents the favorable outcome and 0 represents the unfavorable outcome. (you can use any boolean-like value for this, `1`/`0`, `True`/`False`, `1.0`/`0.0`)

I might be misunderstanding your first question, but if you are asking about passing in deciles as outcomes, this may work but you might run into trouble if there are ties (for example, if the deciles don't break up into 10 even buckets).

If you're looking to use the quantile categories themselves as the `outcome`, you may be interested in `categorical_adverse_impact_ratio`. An example of how to use this function can be found in [example notebook 02](https://github.com/SolasAI/solas-ai-disparity/blob/main/examples/02_solas-ai-disparity-calculations.ipynb) in this repo.

For `adverse_impact_ratio_by_quantile` the `outcome` will likely be the model's predictions, but could also be scores (e.g. credit score). The function will split predictions/scores according to the quantiles you specify, e.g. using deciles:

```python
airq = sd.adverse_impact_ratio_by_quantile(
	# [...]
	quantiles=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
	# [...]
)
```

As far as documentation:
- You may have already seen our example notebooks, but if you haven't that would be the best place to start. See the `examples/` directory in this repo.
- You may also want to check out the API docs: [PDF](https://solasai.github.io/solas-ai/_static/solasai.pdf)
- Finally, if your notebook/IDE/editor does not allow you to view docstrings on the functions, you can always use `help()`:

```python
help(adverse_impact_ratio)
help(adverse_impact_ratio_by_quantile)
```

If you're still having issues, we can take a look at your function/code if you are able to post it here.

**Comment by stupidoge** [comment]
Hi @mikewilkerson-solas Mike, got that. Actually I am curious about the `adverse_impact_ratio_by_quantile` function. Does this function do cutting by equal-width binning, or equal-frequency binning? 

Also as you said 

> For `adverse_impact_ratio_by_quantile` the `outcome` will likely be the model's predictions, but could also be scores.

Does this mean the outcome coule be a probability from 0.1-1, and also could be some scores with no range limit. But, I cannot be the bool value (0 or 1) right?

Thanks

**Comment by mikewilkerson-solas** [comment]
Hi @stupidoge,

1. `adverse_impact_ratio_by_quantile` uses equal-frequency binning.
2. That is correct: `adverse_impact_ratio_by_quantile` is calculating quantile cut points and calling `adverse_impact_ratio()` based on that. If you already have boolean-like outcomes, there would be no reason to use `adverse_impact_ratio_by_quantile`.

Hope this helps.

**Comment by stupidoge** [comment]
Hi @mikewilkerson-solas, I am so so thanks for your kind reply. I also want to know, `the adverse_impact_ratio_by_quantile` is an accumulative results or a independent? I mean, 20% decile data stands for data from 10%-20%, or data from 0%-20% decile.

Actually, I use qcut() and `adverse_impact_ratio()` to build a function to "calculate accumulative results", but the results are totally different from your `adverse_impact_ratio_by_quantile`. qcut() is a function uses equal-frequency binning, so I think the logic is totally same with yours. When we look back to the results, one said there is no bias, but another said in reverse. Here I give two reasonable explaination.

1.Based on what you said, I guess `adverse_impact_ratio_by_quantile` just calculate the AIR by predict possibility, but `adverse_impact_ratio()` just calculate based on boolean value. 
2.Maybe your results is not accumulative. 

Hope get from your reply. Thanks again for your time and effort.

**Comment by mikewilkerson-solas** [comment]
Hey @stupidoge,

> the adverse_impact_ratio_by_quantile is an accumulative results or a independent? I mean, 20% decile data stands for data from 10%-20%, or data from 0%-20% decile.

It is cumulative. So the 20th percentile would be top 20% v. bottom 80%; 30th percentile would be top 30% v bottom 70%; etc.

> Actually, I use qcut() and `adverse_impact_ratio()` to build a function to "calculate accumulative results", but the results are totally different from your `adverse_impact_ratio_by_quantile`. qcut() is a function uses equal-frequency binning, so I think the logic is totally same with yours. When we look back to the results, one said there is no bias, but another said in reverse.

I would guess that the differences you are seeing between your results using pandas `qcut` and our results are driven by a need to change the specification for `lower_score_favorable`. The default value is `True`, which means that a lower value is preferred by the customer. That would be accurate for something like a probability of default model. However, if your predictions are such that a higher value is favorable (e.g., a marketing model), then you want to set `lower_score_favorable=False`.

**Comment by mikewilkerson-solas** [comment]
Hope this answered your questions! Closing this issue for now, and please feel free to open a new one if you have questions in the future.
